# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sqlite3
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.submit = QtWidgets.QPushButton(self.centralwidget)
        self.submit.setGeometry(QtCore.QRect(280, 360, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(20)
        self.submit.setFont(font)
        self.submit.setObjectName("submit")
        self.accountInput = QtWidgets.QTextEdit(self.centralwidget)
        self.accountInput.setGeometry(QtCore.QRect(300, 150, 241, 51))
        self.accountInput.setObjectName("accountInput")
        self.account = QtWidgets.QLabel(self.centralwidget)
        self.account.setGeometry(QtCore.QRect(150, 160, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(20)
        self.account.setFont(font)
        self.account.setObjectName("account")
        self.password = QtWidgets.QLabel(self.centralwidget)
        self.password.setGeometry(QtCore.QRect(150, 220, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(20)
        self.password.setFont(font)
        self.password.setObjectName("password")
        self.passwordInput = QtWidgets.QTextEdit(self.centralwidget)
        self.passwordInput.setGeometry(QtCore.QRect(300, 220, 241, 51))
        self.passwordInput.setObjectName("passwordInput")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.submit.clicked.connect(self.login)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.submit.setText(_translate("MainWindow", "submit"))
        self.account.setText(_translate("MainWindow", "account"))
        self.password.setText(_translate("MainWindow", "password"))

    def login(self):
        conn = sqlite3.connect('testingDB.db')
        try:
            cur = conn.cursor()
            account = self.accountInput.toPlainText()
            cur.execute(
                "SELECT * FROM member where account =?", (account,))
            row = cur.fetchone()
            if row[1] == self.passwordInput.toPlainText():
                self.show_popup()
        except sqlite3.Error as e:
            print("An error occurred:", e.args[0])

    def show_popup(self):
        msg = QtWidgets.QMessageBox()
        msg.setWindowTitle("title of msg")
        msg.setText("login successfully")
        msg.setIcon(QtWidgets.QMessageBox.information)
        msg.exec_()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
